# Generated by Django 5.0.2 on 2024-03-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_rename_email_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserProfile',
        ),
    ]
